### ISSUE TITLE
No data is shown, like it can't find the debug log file

### ISSUE THREAD

**Issue by realdevnullius** [kubec/chia-log-analyzer#15]
```
./chia-log-analyzer.go-linux-amd64 --log=/home/me/.chia/mainnet/log

pwd
/home/me/.chia/mainnet/log
```

The chia binary wallet is up and running, debug.log shows current system time so it is being used. Basically, I followed the github instructions to the letter and found no problems yet it doesn't work for me. Ubuntu 20.04. Any ideas? :)

**Comment by realdevnullius** [comment]
PS: I'm using plotman for the actual plotting and I tried to run the chia-log-analyzer binary from plotman's logfiles directory directly, but that didn't do anything either.

**Comment by realdevnullius** [comment]
`./chia-log-analyzer.go-linux-amd64 --log=~/.chia/mainnet/log
`

This one works. Closing again :+1:

**Comment by 4ntibala** [comment]
can somebody reopen this issue? i encounter exactly the same on Mint 20.1

`ls ~/.chia/mainnet/log`

`debug.log`

`./chia-log-analyzer.go-linux-amd64 --log=~/.chia/mainnet/debug.log`

the command line UI opens, but it doesnt load any content... :/
