### ISSUE TITLE
Cannot execute binary

### ISSUE THREAD

**Issue by cojarbi** [kubec/chia-log-analyzer#5]
Hi, im just getting a "chia-log-analyzer.go-darwin-amd64: command not found"

Ubuntu 20.04 either by running the full command with the path to the bin or by placing the binary i in the same folder

**Comment by kubec** [comment]
You must set file as executable: `chmod +x  chia-log-analyzer.go-darwin-amd64`

and then: `./chia-log-analyzer.go-darwin-amd64`

I have add these instructions to the homepage now.

**Comment by cojarbi** [comment]
Hi, this is what I'm getting after executing the above

![image](https://user-images.githubusercontent.com/16444438/120678799-7dba4600-c466-11eb-85da-21339434122d.png)

**Comment by kubec** [comment]
Hello!
You must use https://github.com/kubec/chia-log-analyzer/releases/download/0.4.3/chia-log-analyzer.go-linux-amd64 for Ubnutu. chia-log-analyzer.go-darwin-amd64 is binary for MacOS

**Comment by cojarbi** [comment]
Im terribly sorry, running on a mac via ssh to my linux and got confused and into a rabbit hole.

I appreciate the effort and love the tool

**Comment by kubec** [comment]
You're welcom
