### ISSUE TITLE
Error "flag provided but not defined: -log"

### ISSUE THREAD

**Issue by tuedang** [kubec/chia-log-analyzer#9]
Run on window
.\chia-log-analyzer.go-windows-amd64-signed.exe --log=/path/to/debug.log

But received the error

`flag provided but not defined: -log
Usage of .\chia-log-analyzer.go-windows-amd64-signed.exe:
  -writelog
        write log?`

note: `-writelog` is understandable by program

**Comment by kubec** [comment]
Fixed in new release 0.5
